networks:
  backend:

volumes:
  pgdata:
  redisdata:
  csvdata:

services:
  db:
    image: postgres:16
    container_name: iss_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-monolith}
      POSTGRES_USER: ${POSTGRES_USER:-monouser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-monopass}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-monouser} -d ${POSTGRES_DB:-monolith}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./db/migrate_add_osdr_columns.sql:/docker-entrypoint-initdb.d/02-migrate-osdr.sql:ro
    networks:
      - backend
    ports:
      - "${DB_PORT:-5432}:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - backend
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-backend:
    build:
      context: ./services/fastapi-backend
    container_name: fastapi_backend
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER:-monouser}:${POSTGRES_PASSWORD:-monopass}@db:5432/${POSTGRES_DB:-monolith}}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      NASA_API_URL: ${NASA_API_URL:-}
      NASA_API_KEY: ${NASA_API_KEY:-}
      FETCH_EVERY_SECONDS: ${FETCH_EVERY_SECONDS:-600}
      WHERE_ISS_URL: ${WHERE_ISS_URL:-https://api.wheretheiss.at/v1/satellites/25544}
      JWST_HOST: ${JWST_HOST:-https://api.jwstapi.com}
      JWST_API_KEY: ${JWST_API_KEY:-baa96cdf-4a82-45f1-b986-d10a96826442}
      JWST_EMAIL: ${JWST_EMAIL:-burnfeniks@yandex.ru}
      JWST_PROGRAM_ID: ${JWST_PROGRAM_ID:-2734}
      ASTRO_APP_ID: ${ASTRO_APP_ID:-745a5e07-70ae-49fc-8014-6a509551f829}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET:-fe85a6503e3dd694a5d888effb336aefbbb5f54f348a134bd84126de5f69f536c5f05e75a55d395f41ae789b037bed48b7a505a690637acbf2108f5aefe3d934e0ab7b23bf469552d5eb6fc428f8ea981b02323cf3f6ec996ad7b6eab8312f786fd8c25eafc22cea532030c8dc3749c4}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:8080}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "${FASTAPI_PORT:-8081}:8000"

  nextjs-frontend:
    build:
      context: ./services/nextjs-frontend
    container_name: nextjs_frontend
    environment:
      NODE_ENV: production
      API_URL: http://fastapi-backend:8000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8081}
    depends_on:
      - fastapi-backend
    networks:
      - backend
    ports:
      - "${NEXTJS_PORT:-3000}:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      nextjs-frontend:
        condition: service_started
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "${NGINX_PORT:-8080}:80"
    restart: unless-stopped

  pascal-legacy:
    build:
      context: ./services/pascal-legacy
    container_name: pascal_legacy
    environment:
      CSV_OUT_DIR: /data/csv
      GEN_PERIOD_SEC: ${PAS_LEGACY_PERIOD:-300}
      PGHOST: db
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER:-monouser}
      PGPASSWORD: ${POSTGRES_PASSWORD:-monopass}
      PGDATABASE: ${POSTGRES_DB:-monolith}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - csvdata:/data/csv
    networks:
      - backend

